server:
  port: 9001

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/learn_resilience_4j
    username: root
    password: Dhiwakar@2003
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true


resilience4j:
  circuitbreaker:
    instances:
      product-service:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 12s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10
      
      order-service:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 12s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10
      
  timelimiter:
    instances:
      user-service:
       timeout-duration: 13s

     



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
